[project]
name = "mlbuaa2025personalwork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.8.3",
    "lightning>=2.6.0",
    "pillow>=12.1.0",
    "torch>=2.9.1",
    "wandb>=0.23.1",
]
